//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public System.Guid PersonID { get; set; }
        public string PersonName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> DateOfJoining { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> IsRegistered { get; set; }
        public string State { get; set; }
    }
}
